### ISSUE TITLE
Supporting YAML frontmatters for metadata

### ISSUE THREAD

**Issue by mickael-menu** [mickael-menu/zk#1]
Many Zettelkasten use a YAML frontmatter to provide note metadata, e.g.:

```yaml
---
title: Improve the structure of essays by rewriting
date: 2011-05-16 09:58:57
keywords: [writing, essay, practice]
---
```

`zk` only supports `title`, we should support the rest as well:

* `date` for the creation date
* `keywords` and `tags` for tags
* `description` could be used for the lead paragraph

[Neuron](https://neuron.zettel.page/metadata) also supports `unlisted: true` which could be interesting to disable indexing of particular notes.

Unknown keys could be saved and indexed for targeted search.
