### ISSUE TITLE
More date utilities in handlebar template and config file

### ISSUE THREAD

**Issue by rayandrews** [mickael-menu/zk#152]
Hi!
Thank you for this application! It really helps me maintain my second brain.

However, I have specific use cases such as daily planning.
I usually create a plan for tomorrow in the night.
I think it would be good if this application has `{{ date tomorrow (format) }} `.

Or is there any other way to get the tomorrow date?

Thank you again!

**Comment by rayandrews** [comment]
For now I use this hack to make it works.

```bash
#!/usr/bin/env bash

tomorrow=$(date -v+1d +%A-%B-%Y-%m-%d)

arr=(${tomorrow//-/ })

dayname=${arr[0]}
monthname=${arr[1]}
year=${arr[2]}
month=${arr[3]}
day=${arr[4]}
when="$year-$month-$day"

mkdir -p $BRAIN_DIR/plans/$year/$month
cd $BRAIN_DIR
zk new --no-input "plans" \
  --extra dayname="$dayname",monthname="$monthname",when="$when",year="$year",month="$month",day="$day"
```

```toml
[group.plans]
paths = [
    "plans",
]

[group.plans.note]
# uncomment if zk supports {{date tomorrow}}
# filename = "{{date now '%Y'}}/{{date now '%m'}}/{{date now '%Y-%m-%d'}}"
filename = "{{extra.year}}/{{extra.month}}/{{extra.when}}"
extension = "md"
# template = "plan/default.md"
template = "plan/hacky.md"
```

```markdown
---
title: Plan of {{ extra.dayname }}, {{ extra.monthname }} {{ extra.day }}, {{ extra.year }}
description: Plan of {{ extra.dayname }}, {{ extra.monthname }} {{ extra.day }}, {{ extra.year }}
slug: {{ extra.year }}/{{ extra.month }}/{{ extra.day }}
date: {{ extra.when }}
type: plan
keywords:
  - plan
  - plans
roles:
  - super-admin
  - admin
---

What will I do at {{ extra.dayname }}, {{ extra.monthname }} {{ extra.day }}, {{ extra.year }}?
```

Results:

```markdown
---
title: Plan of Tuesday, January 11, 2022
description: Plan of Tuesday, January 11, 2022
slug: 2022/01/11
date: 2022-01-11
type: plan
keywords:
  - plan
  - plans
roles:
  - super-admin
  - admin
---

What will I do at Tuesday, January 11, 2022?
```

Feel free to close this!
If you have any better suggestions, feel free to reply.
This proves that the program is **future-proof** indeed!

Thanks!
