### ISSUE TITLE
Cannot get group overrides to work

### ISSUE THREAD

**Issue by trev-dev** [mickael-menu/zk#202]
No matter what I seem to do I cannot get the filename and the template overrides to work. I always end up with one, or both using the default settings.

zk build: `zk 0.10.0-1-g94f563c`

I have the following configurations:

_In ~/Notes/.zk/config.toml_
```toml
[note]
filename = "{{slug title}}-{{id}}"
template = "default.md"

[group.cookbook]
filename = "{{slug title}}"
template = "recipe.md"

[alias]
recipe = 'zk new --group cookbook --title "$*"'
```

_~/Notes/.zk/templates/recipe.md_
```markdown
---
tags: [recipe]
---

# {{title}}

{{content}}

## Ingredients

## Directions

```

_Directory Structure_
```
~/Notes/
├── cannot-get-group-overrides-to-work-9haz.md
├── cookbook
│   └── index.md
├── neovim-plugins-to-check-out-4p8z.md
├── .stfolder
├── .zettel-notes
│   ├── patches
│   │   └── 1
│   │       └── a53362f1-9975-4182-bb32-8590f830f09c.diff
│   └── recycle-bin
└── .zk
    ├── config.toml
    ├── notebook.db
    └── templates
        ├── default.md
        └── recipe.md

8 directories, 8 files
```

_~/.zshenv_
```bash
export ZK_NOTEBOOK_DIR=$HOME/Notes
```

I have tried:  
`zk recipe "Some title"`  
`zk new --group cookbook --title "Some title"`  
`zk new "$ZK_NOTEBOOK_DIR/cookbook" --title "Some title"`  
`cd ~/Notes && zk new cookbook --title "Some title"`  
`cd ~/Notes/cookbook && zk new --title "Some title"`  
`zk new --template "recipe.md" --title "Some title"` - Template works, `filename` does not.

I can't seem to appreciate what the docs are trying to say to me [in the note group](https://github.com/mickael-menu/zk/blob/main/docs/config-group.md) doc, or [in the journalling](https://github.com/mickael-menu/zk/blob/main/docs/daily-journal.md) doc.

Help?

**Comment by mickael-menu** [comment]
The `filename` and `template` config properties need to be under a `note` sub-section of your group, by adding the `.note` suffix here:

```toml
[group.cookbook.note]
filename = "{{slug title}}"
template = "recipe.md"
```

With this, `zk recipe "Some title"` should work.

At the moment, [only the property `paths` is available under the `[group.x]` section](https://github.com/mickael-menu/zk/blob/main/docs/config-group.md#declaring-a-new-group).
