### ISSUE TITLE
zk lsp fails with custom `link-format`

### ISSUE THREAD

**Issue by dstanberry** [mickael-menu/zk#264]
Version: zk 0.11.1-3-g404ef9d

```toml
[format.markdown]
link-format = "wiki"
```
Until recently I've been using the above settings and have had no issues in neovim with the lsp configuration.

However, after changing the link-format to `"[{{title}}]({{path}})"` I get error "zk: not found". 

Launching the zk binary and specifying a log location doesn't seem to show anything helpful to diagnose this, the handler for `textDocument/definition` just prints 'null'.

https://github.com/mickael-menu/zk/commit/1a05a0443243400356ec11450608364e2299336f#commitcomment-77337988 suggests that this shouldn't be an issue for zk to be able to resolve, so I'm not sure what the cause is. This may be related to #250.

Can you provide any guidance if there is some other setting I may need to modify? Happy to provide any additional information as needed.

**Comment by mickael-menu** [comment]
I can't reproduce this error, using the `[[` completion trigger in nvim and the following TOML config:

```toml
[note]
template = "default.md"
filename = "{{id}}"

[format.markdown]
link-format = "[{{title}}]({{path}})"
```

Maybe check that the directory containing `zk` is properly set in nvim by running `:echo $PATH`?

**Comment by dstanberry** [comment]
The completion works for me as well (and seems to be the only action lsp-wise that works) but `vim.lsp.hover()` fails and results in the error message I mentioned in the initial post.

This is the config I am using:
```toml
[note]
language = "en"
filename = "{{date now '%Y-%m-%d'}}-{{slug title}}"
template = "default.md"
id-charset = "hex"
id-length = 5
id-case = "lower"

[group.journal]
paths = ["inbox", "journal"]
[group.journal.note]
filename = "{{date now '%Y-%m-%d'}}-{{id}}"
extension = "md"
template = "journal.md"

[format.markdown]
hashtags = true
colon-tags = true
# link-format = "wiki"
# link-format = "[[{{filename}}]]"
link-format = "[{{title}}]({{path}})"
link-encode-path = true
link-drop-extension = true
```
