### ISSUE TITLE
`config.toml` should support all environment variable configurations

### ISSUE THREAD

**Issue by lsvmello** [mickael-menu/zk#300]
It would be nice if everything that we are able to configure through environment variables could also be configured in the configuration file.

I didn't found a way to configure `ZK_SHELL` and `ZK_NOTEBOOK_DIR` in the `config.toml` file.

Suggestions:

1. for `ZK_SHELL` add to `tool` configuration
   ```toml
   [tool]
   shell = "/bin/bash"
   ```

2. for `ZK_NOTEBOOK_DIR` add a new configuration group
   ```toml
   [notebook]
   dir = "~/Notes"
   ```
