### ISSUE TITLE
LSP does not work

### ISSUE THREAD

**Issue by ilyss01** [mickael-menu/zk#332]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Error msg:
![image](https://github.com/mickael-menu/zk/assets/47274578/1de1364d-afa4-42e2-8fcd-0dd22d6ce439)

When I try to use autocomplete it doesn't suggest any markdown notes. The only thing that it suggests is words in the file

I have installed `zk` on my system, `zk-nvim` on my nvim. Here are all configs and everything related to the bug:
* Plugins
`/nvim/lua/plugins.lua`
```lua
use 'echasnovski/mini.nvim'
use 'mickael-menu/zk-nvim'
```
* nvim LSP
`nvim/after/plugin/lsp.lua`
```lua
require'zk'.setup({
  picker = 'telescope',
  lsp = {
    config = {
      cmd = { 'zk', 'lsp' },
      name = 'zk',
      -- on_attach = ...
    },
    auto_attach = {
      enabled = true,
      filetypes = { 'markdown' },
    },
  },
})
```
* Completion
`nvim/after/plugin/mini.lua`
```lua
require('mini.completion').setup()
```

### How to reproduce?

I am located in notebook directory
```bash
nvim . # doesn't work
nvim CS.md # doesn't work either
```

### zk configuration

```toml
[note]
language = "en"
default-title = "Untitled"
filename = "{{title}}"
extension = "md"
template = "default.md"

# Path globs ignored while indexing existing notes.
#ignore = [
#    "drafts/*",
#	"log.md"
#]

# Configure random ID generation.

# The charset used for random IDs. You can use:
#   * letters: only letters from a to z.
#   * numbers: 0 to 9
#   * alphanum: letters + numbers
#   * hex: hexadecimal, from a to f and 0 to 9
#   * custom string: will use any character from the provided value
#id-charset = "alphanum"

# Length of the generated IDs.
#id-length = 4

# Letter case for the random IDs, among lower, upper or mixed.
#id-case = "lower"


[extra]

#key = "value"


# GROUP OVERRIDES
#
# You can override global settings from [note] and [extra] for a particular
# group of notes by declaring a [group."<name>"] section.
#
# Specify the list of directories which will automatically belong to the group
# with the optional `paths` property.
#
# Omitting `paths` is equivalent to providing a single path equal to the name of
# the group. This can be useful to quickly declare a group by the name of the
# directory it applies to.

#[group."<NAME>"]
#paths = ["<DIR1>", "<DIR2>"]
#[group."<NAME>".note]
#filename = "{{format-date now}}"
#[group."<NAME>".extra]
#key = "value"


# MARKDOWN SETTINGS
[format.markdown]
link-format = "wiki"
link-encode-path = false
link-drop-extension = true
hashtags = true
colon-tags = false
multiword-tags = true


[tool]
editor = "nvim"
shell = "/usr/bin/zsh"
fzf-preview = "bat -p --color always {-1}"
# Pager used to scroll through long output. If you want to disable paging
# altogether, set it to an empty string "".
#pager = "less -FIRX"


# Enable LSP
[lsp]


[lsp.diagnostics]
# Each diagnostic can have for value: none, hint, info, warning, error

# Report titles of wiki-links as hints.
wiki-title = "none"
# Warn for dead links between notes.
dead-link = "error"


[lsp.completion]
# Customize the completion pop-up of your LSP client.

# Show the note title in the completion pop-up, or fallback on its path if empty.
note-label = "{{path}}"
# Filter out the completion pop-up using the note title or its path.
note-filter-text = "{{title}}"
# Show the note filename without extension as detail.
note-detail = "{{path}}"


# NAMED FILTERS
#
#    A named filter is a set of note filtering options used frequently together.
#
[filter]

# Matches the notes created the last two weeks. For example:
#    $ zk list recents --limit 15
#    $ zk edit recents --interactive
#recents = "--sort created- --created-after 'last two weeks'"


# COMMAND ALIASES
#
#   Aliases are user commands called with `zk <alias> [<flags>] [<args>]`.
#
#   The alias will be executed with `$SHELL -c`, please refer to your shell's
#   man page to see the available syntax. In most shells:
#     * $@ can be used to expand all the provided flags and arguments
#     * you can pipe commands together with the usual | character
#
[alias]
# Here are a few aliases to get you started.

# Shortcut to a command.
#ls = "zk list $@"

# Default flags for an existing command.
#list = "zk list --quiet $@"

# Edit the last modified note.
#editlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
# This alias doesn't take any argument, so we don't use $@.
#recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Print paths separated with colons for the notes found with the given
# arguments. This can be useful to expand a complex search query into a flag
# taking only paths. For example:
#   zk list --link-to "`zk path -m potatoe`"
#path = "zk list --quiet --format {{path}} --delimiter , $@"

# Show a random note.
#lucky = "zk list --quiet --format full --sort random --limit 1"

# Returns the Git history for the notes found with the given arguments.
# Note the use of a pipe and the location of $@.
#hist = "zk list --format path --delimiter0 --quiet $@ | xargs -t -0 git log --patch --"

# Edit this configuration file.
#conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
```

### Environment

```bash
zk 0.14.0
system: Linux 6.3.7-zen1-1-zen x86_64 GNU/Linux
```
