### ISSUE TITLE
`zk new` ignores standard input

### ISSUE THREAD

**Issue by dc6c** [mickael-menu/zk#544]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

`zk new` always opens an empty editor regardless of what's pasted into it

### How to reproduce?

1. run `echo hello | zk new --interactive`
2. zk opens the editor with empty contents

### zk configuration

```toml
[notebook]
dir = "~/daily-journal"

[tool]
editor="vim"
```

### Environment

```bash
zk 0.15.1-1-g6fc9b01
system: Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 GNU/Linux
```
