### ISSUE TITLE
alias is not known/executed if -W option is given first

### ISSUE THREAD

**Issue by systemplado** [mickael-menu/zk#66]
i have initialized a notebook at `~/notes` and running the command `zk ls -W ~/notes`, on a different directory, returns the correct output (all the notes in oneline format).
however, running the command `zk -W ~/notes ls` returns the following with an exit code of 1
```
Usage: zk <command>

NOTEBOOK
  A notebook is a directory containing a collection of notes

  init     Create a new notebook in the given directory.
  index    Index the notes to be searchable.

NOTES
  Edit or browse your notes

  new     Create a new note in the given notebook directory.
  list    List notes matching the given criteria.
  edit    Edit notes matching the given criteria.

Flags:
  -h, --help                 Show context-sensitive help.
      --notebook-dir=PATH    Turn off notebook auto-discovery and set manually
                             the notebook where commands are run.
  -W, --working-dir=PATH     Run as if zk was started in <PATH> instead of the
                             current working directory.
      --no-input             Never prompt or ask for confirmation.

Run "zk <command> --help" for more information on a command.

zk: error: unexpected argument ls, did you mean "list"?
```

here is my `~/notes/.zk/config.toml`
```toml
[note]
template = "default.md"

[extra]


[format.markdown]
hashtags = true
colon-tags = false
multiword-tags = false

[tool]


[lsp]


[lsp.diagnostics]
dead-link = "error"

[filter]


[alias]
journal = "zk new journal -g journal --no-input"
ls = "zk list --format oneline $@"

[group.journal]


[group.journal.note]
filename = "{{date now}}"
template = "journal.md"

```

moreover, if i use the command `zk -W ~/notes list --format oneline`, it returns the same output as `zk ls -W ~/notes`. native commands such as `new`, `edit`, and `list` seems to be working fine regardless of the position of the -W option.

i have also tried removing the `$@` from the `ls` alias in my `~/notes/.zk/config.toml` and i still get the same results. the output is also quite similar if i test the `journal` alias with the last line being `zk: error: unexpected argument journal` instead.

is this the intended behavior that zk aliases wont work if the `-W <path>` option is given first before the alias?

i found out this behavior since i wanted to create a shell alias (`alias zknotes="zk -W ~/notes"`) but it turns out that it will not work properly if i used zk aliases as well.
